<Project Sdk="Microsoft.NET.Sdk.WindowsDesktop">
  <PropertyGroup>
    <Configurations>Developer - Debug;Release - Alpha;Release - Beta;Release - Final</Configurations>
    <Platforms>x64</Platforms>
    <TargetFramework>net48</TargetFramework>
    <AssemblyTitle>FlurryEditorPlugin</AssemblyTitle>
    <Product>FlurryEditorPlugin</Product>
    <RootNamespace>Flurry.Editor</RootNamespace>
    <Copyright>Copyright © 2025</Copyright>
    <CodeAnalysisRuleSet>MinimumRecommendedRules.ruleset</CodeAnalysisRuleSet>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
    <UseWPF>true</UseWPF>
    <OutputType>Library</OutputType>
    <WeaverConfiguration>
      <Weavers>
        <Costura>
          <!-- Only embed these runtime assemblies -->
          <IncludeAssemblies>
            DiffPlex
            DiffPlex.Wpf
            0Harmony
          </IncludeAssemblies>
        </Costura>
      </Weavers>
    </WeaverConfiguration>
  </PropertyGroup>

  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Developer - Debug|x64' ">
    <DebugSymbols>true</DebugSymbols>
    <OutputPath>bin\Developer\Debug\</OutputPath>
    <DefineConstants>DEBUG;TRACE</DefineConstants>
  </PropertyGroup>

  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Release - Alpha|x64' ">
    <OutputPath>bin\Release\Alpha\</OutputPath>
    <DefineConstants>TRACE</DefineConstants>
    <Optimize>true</Optimize>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)' == 'Release - Beta|x64'">
    <OutputPath>bin\Release\Beta\</OutputPath>
    <DefineConstants>TRACE</DefineConstants>
    <Optimize>true</Optimize>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)' == 'Release - Final|x64'">
    <OutputPath>bin\Release\Final\</OutputPath>
    <DefineConstants>TRACE</DefineConstants>
    <Optimize>true</Optimize>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Costura.Fody" Version="6.0.0">
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="DiffPlex.Wpf" Version="1.9.1">
      <Private>false</Private>
    </PackageReference>
    <PackageReference Include="Lib.Harmony" Version="2.4.2">
      <Private>false</Private>
    </PackageReference>
    <PackageReference Include="Microsoft.CSharp" Version="4.7.0">
      <Private>false</Private>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <Reference Include="FrostyControls">
      <HintPath>$(FrostyEditorInstallationPath)\FrostyControls.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="FrostyHash">
      <HintPath>$(FrostyEditorInstallationPath)\FrostyHash.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="FrostyCore">
      <HintPath>$(FrostyEditorInstallationPath)\FrostyCore.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="FrostySdk">
      <HintPath>$(FrostyEditorInstallationPath)\FrostySdk.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="FrostyEditor">
      <HintPath>$(FrostyEditorInstallationPath)\FrostyEditor.exe</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="ReferencesPlugin">
      <HintPath>$(FrostyEditorInstallationPath)\Plugins\ReferencesPlugin.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="BundleEditorPlugin">
      <HintPath>$(FrostyEditorInstallationPath)\Plugins\BundleEditorPlugin.dll</HintPath>
      <Private>false</Private>
    </Reference>
  </ItemGroup>

  <ItemGroup>
    <Resource Include="Images\KyberCog.png" />
    <Resource Include="Images\Pencil.png" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="MeshSetPlugin">
      <HintPath>$(FrostyEditorInstallationPath)\Plugins\MeshSetPlugin.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="ChunkResEditorPlugin">
      <HintPath>$(FrostyEditorInstallationPath)\Plugins\ChunkResEditorPlugin.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="DuplicationPlugin">
      <HintPath>$(FrostyEditorInstallationPath)\Plugins\DuplicationPlugin.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="0Harmony">
      <HintPath>ThirdParty\0Harmony.dll</HintPath>
    </Reference>
    <Reference Include="Newtonsoft.Json">
      <HintPath>$(FrostyEditorInstallationPath)\ThirdParty\Newtonsoft.Json.dll</HintPath>
    </Reference>
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Data\FacePoserMappings.json" />
    <EmbeddedResource Include="Data\WeaponMappings.json" />
  </ItemGroup>

  <!--
    <Target Name="PostBuild" AfterTargets="PostBuildEvent">
      <Exec Command="xcopy /Y $(TargetPath) $(SolutionDir)$(OutDir)Plugins\" />
    </Target>
  -->

</Project>